name: Push to Aliyun
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun
        run: |
          # 替换下面两个词：比如 --username=aitaoyao@aliyun.com --password=MyPassword123
          docker login --username=15866632935 --password=heqiang930715 registry.cn-hangzhou.aliyuncs.com

      - name: Pull and Push
        run: |
          docker pull fullstackjack/fastapi-best-architecture:latest
          
          # 下面这两行的 [命名空间] 也要换掉
          docker tag fullstackjack/fastapi-best-architecture:latest registry.cn-hangzhou.aliyuncs.com/aitaoyao_test/fastapi-practice:latest
          docker push registry.cn-hangzhou.aliyuncs.com/aitaoyao_test/fastapi-practice:latest
